// Cucumber-js configuration (ADR-0016). Executes the real .feature files against the
// headless engine. The `name` include-list scopes the run to the scenarios whose
// behaviour Phase 1 actually implements; scenarios that need later phases — the audio
// engine (Phase 5), Auto Take (Phase 6), digital effects (Phase 3), or browser
// permission/enumeration, plus @wip — are simply not selected, so the domain-test layer
// stays green and honest. Step files are TypeScript, loaded via the tsx runtime.

export default {
  paths: [
    'features/inputs-and-devices.feature',
    'features/source-selection.feature',
    'features/program-output.feature',
    'features/transition-mix-nam.feature',
    'features/matte-generator.feature',
    'features/wipe-patterns.feature',
    'features/wipe-edge-and-direction.feature',
    'features/color-correction.feature',
    'features/digital-effects-filters.feature',
    'features/digital-effect-still.feature',
    'features/digital-effect-strobe.feature',
    'features/digital-effect-multi.feature',
    'features/digital-effect-trail.feature',
    'features/position-and-scene-grabber.feature',
    'features/luminance-key.feature',
    'features/chroma-key.feature',
    'features/downstream-key.feature',
    'features/audio-mixer.feature',
    'features/audio-follow.feature',
    'features/av-synchro.feature',
  ],
  import: [
    'test/features/support/world.ts',
    'test/features/steps/inputs-and-devices.steps.ts',
    'test/features/steps/mixer.steps.ts',
    'test/features/steps/wipe.steps.ts',
    'test/features/steps/effects.steps.ts',
    'test/features/steps/freeze.steps.ts',
    'test/features/steps/positioner.steps.ts',
    'test/features/steps/keys.steps.ts',
    'test/features/steps/dsk.steps.ts',
    'test/features/steps/audio.steps.ts',
    'test/features/steps/av-synchro.steps.ts',
  ],
  name: [
    // inputs-and-devices (Rule 1)
    'Binding a source input to a media provider',
    'Rebinding a source replaces its previous provider',
    'An image binding presents as a still video frame',
    'The same media provider may back more than one source',
    // source-selection
    'Assigning an external source to a bus',
    'Selecting a source binds its audio to the matching bus fader',
    'The two buses hold sources independently',
    'Reselecting on the same bus replaces the previous source',
    'The same external source may feed both buses at once',
    'Matte is a valid source for transition stages',
    'Matte is substituted where a function needs real video',
    'The blinking button identifies which real source stands in for Matte',
    'Selecting Matte does not disturb the bus audio routing',
    // program-output
    'EFFECT is the default program output mode',
    'The A button sends the A-bus directly',
    'The B button sends the B-bus directly',
    'The EFFECT button sends the fully processed composite',
    'Direct-out buttons carry only their bus audio',
    'Preview always shows the effected video regardless of program mode',
    'Preview shows the effected video even in EFFECT mode',
    'Preview lets me monitor the effect while sending a clean bus',
    'Matte on the A-bus with direct-out A outputs the blinking source',
    'Matte on the B-bus with direct-out B outputs the blinking source',
    'Matte on a bus is still usable through the EFFECT output',
    'Selecting a program mode deactivates the other two',
    // transition-mix-nam (excludes @integration Auto Take + digital-effect)
    'Selecting MIX arms a cross-dissolve between the two buses',
    'MIX with the lever fully at A shows only the A-bus',
    'MIX with the lever fully at B shows only the B-bus',
    'MIX at lever centre averages the two pictures equally',
    'MIX blends the two buses in proportion to lever travel',
    'MIX travel drives a smooth continuous dissolve',
    'Selecting NAM arms a brightness-based composite',
    'NAM at lever centre keeps the brighter of the two images per pixel',
    'NAM lets bright highlights punch through dark areas',
    'NAM at centre is distinct from a MIX average',
    'Moving the NAM lever off-centre biases which bus dominates',
    'A Matte colour is a valid source for MIX',
    'A Matte colour is a valid source for NAM',
    // matte-generator (excludes @wip White+gradation)
    'SELECT . cycles upward through the palette',
    'SELECT . wraps from the last colour back to the first',
    'Black follows Colour Bar when cycling upward',
    'SELECT . reverses the direction',
    'SELECT . wraps from the first colour back to the last',
    'LEVEL adjusts the chroma of a chromatic colour',
    'Colour Bar and Black ignore the LEVEL control',
    'For White, LEVEL adjusts brightness instead of chroma',
    'GRADATION produces a top-to-bottom vertical gradient',
    'The gradient bottom tracks the LEVEL setting',
    'Disabling GRADATION restores a flat matte',
    // wipe-patterns (excludes the underivable generic-illegal Outline + @wip)
    'Each Pattern Select button cycles through its variants',
    'The Square family grows a shape outward',
    'Selecting a base family with no modifiers yields a plain wipe',
    'Compression pressed once compresses only the incoming scene',
    'Compression pressed twice compresses both scenes',
    'Slide pressed once slides the incoming image over the other',
    'Slide pressed twice slides both images over each other',
    'Multi repeats the wipe pattern up to six times',
    'Multi offers at most six modes',
    'Pairing creates a mirrored wipe scene',
    'Pairing combines with Multi',
    'Blinds render the wipe as venetian-blind strips on compatible families',
    'Blinds on an unsupported family is rejected',
    'A valid combination keeps every engaged modifier LED lit',
    'A composed pattern shows its number on the Wipe Pattern Indicator',
    'Pattern 001 is the normal straight wipe',
    'Adding 128 to a pattern number reverses that same wipe',
    'The reverse of a pattern is its number plus 128',
    'RS422 can address pattern numbers 001 through 255',
    'The AG-A800 edit controller can only call patterns 01 through 99',
    // wipe-edge-and-direction (excludes @integration)
    'First BORDER press draws a narrow coloured border',
    'Second BORDER press widens the border',
    'Third BORDER press turns the border off',
    'BORDER cycles back to narrow on a fourth press',
    'BORDER paints the complement of the current Matte colour',
    'Changing the Matte colour recolours an active border',
    'First SOFT press applies a narrow feathered edge',
    'Second SOFT press widens the feathered edge',
    'SOFT ignores the Matte colour entirely',
    'BORDER and SOFT are mutually exclusive edge treatments',
    'By default the wipe alternates direction each lever swing',
    'ONE-WAY makes every swing travel the same direction',
    'REVERSE mirrors the direction of travel',
    'ONE-WAY combined with REVERSE produces symmetrical wiping',
    'ASPECT stretches a Square-family pattern along one axis',
    'ASPECT centred leaves the Square-family pattern unstretched',
    'ASPECT has no effect on non-Square wipe families',
    // color-correction (excludes the already-B&W-source scenario: needs source content)
    'First press activates CHROMA only',
    'Second press adds the RGB joystick',
    'Third press turns correction off',
    'The button cycles through the three states in order',
    'CHROMA at centre preserves the original saturation',
    'Lowering CHROMA de-saturates toward black-and-white',
    'CHROMA at MIN yields a black-and-white image',
    'From black-and-white the joystick casts a single mono tint',
    'The joystick direction determines the mono tint colour',
    'The RGB joystick at centre preserves the original colour balance',
    'The joystick shifts hue and colour balance when CHROMA is above MIN',
    'The Mono digital effect overrides colour correction',
    'The two buses correct independently',
    'Identical correction on both buses keeps a transition free of colour shift',
    'Mismatched correction produces a visible colour shift across a transition',
    // digital-effects-filters
    'Choosing a bus alone does not change the picture',
    'The effect becomes live only when ON is pressed',
    'An effect applies to only one bus at a time',
    'Turning the effect off restores the untreated bus',
    'Each filter effect activates on the selected bus when ON is pressed',
    'Nega inverts the image like a film negative',
    'Colour Correction stacks on top of Nega',
    'Mosaic breaks the picture into solid-coloured squares',
    'The SIZE control varies the block size across 31 steps',
    'Sweeping the SIZE control animates the pixelation live',
    'Mono converts the bus to black-and-white',
    'Mono overrides colour correction on that bus',
    'Colour correction resumes on the bus when Mono is turned off',
    'Paint posterizes the image to resemble an oil painting',
    'The LEVEL control adjusts the gradation continuously',
    'Sweeping the LEVEL control animates the posterization live',
    // digital-effect-still
    'Engaging Still captures and holds the current frame',
    'The freeze is instantaneous, not a gradual capture',
    'Disengaging Still returns the bus to the live source',
    'Re-engaging Still captures a fresh frame',
    'Engaging a conflicting effect switches Still off automatically',
    'Still cannot be engaged on top of a conflicting effect',
    'Still and Strobe are mutually exclusive',
    'Engaging Trail while Still is active keeps both running',
    'The Still LED blink distinguishes Still-with-Trail from Still alone',
    'Disengaging Trail returns the Still LED to steady',
    'Engaging Still while Trail is already running combines them',
    // digital-effect-strobe (excludes @integration av-synchro + @deferred frame mode)
    'Engaging Strobe steps the bus through frozen frames',
    'Disengaging Strobe returns the bus to live motion',
    'The TIME control sets the freeze interval across its range',
    'The TIME control is clamped to the supported interval range',
    'Adjusting TIME while Strobe runs changes the interval live',
    'Strobe and Still are mutually exclusive on a bus',
    'Engaging Still cancels a running Strobe',
    'Compression is unavailable while Strobe is active',
    'Strobe runs independently per bus',
    // digital-effect-multi
    'The first press splits the picture into 4 images',
    'The second press splits the picture into 9 images',
    'The third press splits the picture into 16 images',
    'The fourth press returns to a single image and ends Multi',
    'Pressing the Multi button cycles through the grid counts in order',
    'The TIME control sets the tile-capture interval',
    'A shorter TIME setting fills the grid faster',
    'ONCE captures each tile a single time through the grid, then freezes',
    'REPEAT cycles through the tiles continuously',
    'Switching from ONCE to REPEAT resumes continuous capture',
    'Engaging Multi switches Still off automatically',
    'Multi tiles only the bus it is assigned to',
    // digital-effect-trail
    'Selecting Trail without ON does not change the picture',
    'Trail becomes live only when ON is pressed',
    'Turning Trail off restores the untreated bus',
    'The live image is compressed and leads the trail',
    'The trail is capped at 16 copies',
    'The Positioner Joystick selects the start corner',
    'The TIME control sets the interval between copies',
    'A shorter interval packs the copies more densely',
    'Moving the joystick mid-trail staggers the image series',
    'A/V Synchro cannot be combined with Trail',
    'Trail cannot be combined with A/V Synchro',
    'The Compression Wipe is unreliable during Trail',
    'Trail applies to only one bus at a time',
    // position-and-scene-grabber (excludes @integration)
    'Positioner engages only with Square-family patterns',
    'Switching away from a Square-family pattern disengages the Positioner',
    'ASPECT shapes the Square pattern when lit',
    'ASPECT has no effect when its ON button is unlit',
    'The wiped size doubles when the Positioner is switched on',
    'The Mix.Wipe lever controls the size of the inset',
    'The joystick places the inset anywhere on screen',
    'Pressing SCENE GRABBER freezes the image inside the inset',
    'After grabbing, the joystick moves the still independently of the live video',
    'The grabbed still holds its size while being moved',
    'Switching the Positioner off releases a grabbed still',
    // luminance-key (all)
    'Engaging Luminance Key with the lever fully at B',
    'The B-bus is always the key source and the A-bus is always the background',
    'Disengaging Luminance Key returns to an ordinary transition',
    'Pixels darker than the slice level become transparent',
    'A white title on a black field keys cleanly over the A-bus',
    'Raising the slice level keys out progressively brighter detail',
    'Lowering the slice toward black keys the whole B-bus image in',
    'Raising the slice toward white keys almost the whole B-bus image out',
    'The lever fully at B shows the key at full opacity',
    'Easing the lever toward A makes the whole keyed foreground translucent',
    'Lever position controls the opacity of the keyed foreground',
    'Returning the lever fully to A dissolves the key away entirely',
    'Changing the slice reshapes the key without changing its opacity',
    'Changing the lever changes opacity without changing which regions are keyed',
    // chroma-key (excludes @integration)
    'Engaging Chroma Key selects it as the active transition function',
    'With the lever fully at B, a fully keyed composite is produced',
    'SLICE starts at centre as the baseline before tuning',
    'HUE selects which colour is removed from the B-bus image',
    'HUE can key out any solid backdrop colour',
    'Fine-tuning SLICE tightens the key edge',
    'SLICE controls the colour-matching tolerance of the key',
    'The B-bus is always the key source regardless of assignment',
    'Easing the lever toward A blends the keyed and unkeyed images',
    'Lever position scales the blend between keyed and unkeyed images',
    'A well-lit stable subject yields the cleanest key',
    'Matte cannot serve as the Chroma Key source',
    // downstream-key (excludes @integration)
    'The DSK keys on top of the finished composite',
    'The DSK is upstream of the Fade stage',
    'Turning the DSK ON reveals the fill in the keyed characters',
    'With the DSK OFF the key is not applied',
    'The two key-level sliders define the luminance window for the title',
    'Trimming the Low Level slider cleans white lettering on a black card',
    'Trimming the High Level slider cleans black lettering on a white card',
    'A character generator keyboard uses both sliders at the low end',
    'Choosing the fill sets the colour inside the keyed characters',
    'The MATTE fill follows the selected Matte Generator colour',
    'Choosing the key source selects where the title luminance comes from',
    'EXT. CAMERA supplies the dedicated title input',
    'The EDGE button cycles through the five edge styles in order',
    'The Normal edge style adds no border or shadow',
    'A white key allows the edge to be coloured with a matte colour',
    'The white-key edge can be graded with GRADATION',
    'A matte-colour key forces the edge to black',
    'REVERSE inverts the key polarity',
    'Pressing REVERSE again restores the original polarity',
    // audio-mixer (all)
    'A Fader follows the source assigned to the A-bus',
    'B Fader follows the source assigned to the B-bus',
    'Master Fader scales the entire mix',
    'Balancing the input faders around 0 dB',
    'Mic-versus-Aux2 switch chooses the shared fader source',
    'EFFECT Program Out passes the full mixed audio',
    'Direct A/B Program Out passes only that bus plus aux and mic',
    'Full mix requires the EFFECT selection',
    'Aux and Mic pass through on every Program Out selection',
    // audio-follow (excludes @integration Auto Take)
    'Audio Follow is off by default and buses obey their own faders',
    'Engaging Audio Follow ties the bus levels to the lever',
    'Bus audio levels track the lever position proportionally',
    'Audio crossfades continuously as the lever sweeps',
    'Aux 1 and Mic/Aux 2 are excluded from Audio Follow',
    'Disengaging Audio Follow returns buses to their standing faders',
    // av-synchro (excludes the deferred Trail-wins scenario)
    'Below-threshold audio leaves the picture untreated',
    'Audio crossing the threshold pulses the effect on',
    'The effect releases when the audio falls back below threshold',
    'A rhythmic audio track pulses the effect in time with the sound',
    'The LEVEL control sets how loud the audio must be to trigger',
    'Turning LEVEL toward MAX rejects all but the loudest peaks',
    'Turning LEVEL toward MIN lets quiet sounds trigger too',
    'Hold time for the non-Strobe effects equals the time above threshold',
    'Strobe hold time is governed by the Effect Interval Timer, not the audio duration',
    'Any combination of the eligible effects can be pulsed together',
    'Each eligible effect can be driven by A/V Synchro',
    'A/V Synchro cannot be combined with Trail',
    'Silence holds every armed effect off',
  ],
};
